language: python
python:
  - 3.6
  - 3.7

cache:
  - pip

install:
  - pip install flake8 tox
before_script:
  - flake8
script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always
